version: "3.8"

services:
  web:
    build:
      context: .                             # Dockerfile is at project root
    command: ["sh", "/app/start.sh"]          # Executes your correct start.sh
    env_file:
      - .env                                 # Reads environment variables from your .env
    depends_on:
      - postgres_db
    restart: always
    expose:
      - "8000"                               # Only available inside Docker network (not exposed to outside!)

  postgres_db:
    image: postgres:17                      # Pinned Postgres version for stability
    restart: always
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "80:80"                              # NGINX exposed to outside world on port 80
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

volumes:
  postgres_data: