name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ secrets.SQL_NAME || 'dummy_db' }}
          POSTGRES_USER: ${{ secrets.SQL_USER || 'dummy_user' }}
          POSTGRES_PASSWORD: ${{ secrets.SQL_PASSWORD || 'dummy_pass' }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SQL_NAME: ${{ secrets.SQL_NAME || 'dummy_db' }}
      SQL_USER: ${{ secrets.SQL_USER || 'dummy_user' }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD || 'dummy_pass' }}
      SQL_HOST: localhost
      SQL_PORT: 5432
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY || 'dummy-ci-key' }}
      DEBUG: 1
      DJANGO_SETTINGS_MODULE: ammentor_backend.settings

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: ⚙️ Run Django setup
        run: |
          python manage.py makemigrations --no-input
          python manage.py migrate --no-input
          python manage.py collectstatic --no-input --clear

      - name: Run tests
        run: python manage.py test